// @generated by imgui-sys-bindgen
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::all)]

#[cfg(all(feature = "docking", feature = "wasm"))]
mod bindings {
    include!("wasm_docking_bindings.rs");
}

#[cfg(all(feature = "docking", not(feature = "wasm")))]
mod bindings {
    include!("docking_bindings.rs");
}

#[cfg(all(not(feature = "docking"), not(feature = "wasm")))]
mod bindings {
    include!("bindings.rs");
}

#[cfg(all(not(feature = "docking"), feature = "wasm"))]
mod bindings {
    include!("wasm_bindings.rs");
}

pub use bindings::*;
